import 'package:flutter/material.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();

  factory LocalizationService() {
    return _instance;
  }

  LocalizationService._internal();

  Locale _locale = const Locale('en');

  Locale get locale => _locale;

  void setLocale(Locale locale) {
    _locale = locale;
  }

  String getLanguageName(String code) {
    switch (code) {
      case 'ar':
        return 'العربية';
      case 'fr':
        return 'Français';
      case 'en':
      default:
        return 'English';
    }
  }

  static const Map<String, Map<String, String>> translations = {
    'en': {
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'french': 'Français',
      'arabic': 'Arabic',
      'sign_out': 'Sign Out',
      'account': 'Account',
      'about': 'About',
      'help': 'Help',
      'privacy': 'Privacy Policy',
      'terms': 'Terms of Service',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'app_name': 'Adhera',
      'welcome': 'Welcome',
      'sign_in': 'Sign In to Your Account',
      'email': 'Email',
      'password': 'Password',
      'remember_me': 'Remember Me',
      'forgot_password': 'Forgot Password?',
      'sign_in_button': 'Sign In',
      'enter_email_required': 'Please enter your email',
      'enter_email_valid': 'Please enter a valid email address',
      'enter_password_required': 'Please enter your password',
      'password_min_6': 'Password must be at least 6 characters',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign Up',
      'tracking': 'Tracking',
      'add_dose': 'Add Dose',
      'mark_taken': 'Mark as Taken',
      'medication': 'Medication',
      'dose': 'Dose',
      'date': 'Date',
      'time': 'Time',
      'cancel': 'Cancel',
      'add': 'Add',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'confirm': 'Confirm',
      'days': 'days',
      'kg_unit': 'kg',
      'logout_message': 'Are you sure you want to sign out?',
      'successfully_signed_in': 'Successfully signed in!',
      'incorrect_credentials': 'Incorrect email or password. Please try again.',
      'forgot_password_soon': 'Forgot password feature coming soon',
      'demo_login': 'Demo Login',
      'demo_doctor_login': 'Demo Doctor',
      'demo_patient_1_login': 'Demo Patient 1',
      'demo_patient_2_login': 'Demo Patient 2',
      'sex_male': 'Male',
      'sex_female': 'Female',
      'exit_app': 'Exit App?',
      'exit_app_message': 'Are you sure you want to exit the app?',
      'exit': 'Exit',
      'treatment': 'Treatment',
      'symptoms': 'Symptoms',
      'insights': 'Insights',
      'profile': 'Profile',
      'patients': 'Patients',
      'alerts': 'Alerts',
      'todays_dose': "Today's Dose",
      'current_streak': 'Current Streak',
      'day': 'Day',
      'days_left': 'Days Left',
      'patient_profile_not_found': 'Patient profile not found.',
      'unknown_patient': 'Unknown Patient',
      'no_email': 'No email',
      'age': 'Age',
      'sex': 'Sex',
      'not_set': 'Not set',
      'weight': 'Weight',
      'treatment_start': 'Treatment Start',
      'treatment_overview': 'Treatment Overview',
      'current_phase': 'Current Phase',
      'day_in_treatment': 'Day in Treatment',
      'of_180': ' of 180',
      'not_started': 'Not started',
      'treatment_calendar': 'Treatment Calendar',
      'calendar': 'Calendar',
      'protocol': 'Protocol',
      'track_treatment_journey':
          'Track each day of your treatment journey and quickly find today.',
      'intensive_phase': 'Intensive Phase',
      'continuation_phase': 'Continuation Phase',
      'phase_1_intensive': 'Phase 1 - Intensive (First 2 months)',
      'phase_2_continuation': 'Phase 2 - Continuation (Months 3-6)',
      'erip_k4': 'ERIP-K4',
      'riniazide': 'RINIAZIDE',
      'erip_2_months': 'ERIP - 2 months',
      'ri_4_months': 'RI - 4 months',
      'goal': 'Goal',
      'remaining': 'Remaining',
      'today': 'Today',
      'daily_timeline': 'Daily Timeline',
      'your_treatment_timeline': 'Your Treatment Timeline',
      'start_date': 'Start date',
      'phase_2_begins': 'Phase 2 begins',
      'expected_end': 'Expected end',
      'important': 'Important',
      'what_this_means_for_you': 'What this means for you',
      'what_you_may_notice': 'What you may notice',
      'why_multiple_medications': 'Why multiple medications?',
      'why_continue_treatment': 'Why continue treatment?',
      'phase_1_goal':
          'Quickly reduce the number of tuberculosis bacteria in your body.',
      'phase_1_feel_better': 'You may start to feel better during this phase',
      'phase_1_symptoms_improve':
          'Symptoms like cough, fever, and fatigue often improve',
      'phase_1_treatment_must_continue':
          'Even if you feel better, treatment must continue',
      'phase_1_kill_faster': 'They kill bacteria faster',
      'phase_1_prevent_resistance':
          'They help prevent the bacteria from becoming resistant',
      'phase_1_complete_recovery':
          'They increase the chances of complete recovery',
      'phase_1_improvement_in_symptoms': 'Improvement in symptoms',
      'phase_1_possible_side_effects':
          'Possible side effects like nausea, fatigue, or orange urine with rifampicin',
      'phase_1_important_note':
          'Do not skip doses. Missing doses in this phase increases the risk of resistance.',
      'phase_2_goal':
          'Eliminate remaining bacteria and prevent the disease from coming back.',
      'phase_2_feel_better': 'You will usually feel much better',
      'phase_2_fewer_medications':
          'There are fewer medications, but treatment is still essential',
      'phase_2_complete_cure':
          'This phase ensures complete cure, not just improvement',
      'phase_2_bacteria_remain':
          'Some bacteria remain in a slow or inactive state',
      'phase_2_harder_to_kill': 'These bacteria are harder to kill',
      'phase_2_relapse_if_stop_early':
          'They can cause relapse if treatment stops early',
      'phase_2_symptoms_mostly_gone': 'Symptoms are mostly gone',
      'phase_2_routine_feels_easier':
          'Your routine may feel easier because there are fewer pills',
      'phase_2_important_note':
          'Stopping treatment early can lead to relapse and drug-resistant tuberculosis, which is much harder to treat.',
      'please_sign_in': 'Please sign in to view insights.',
      'statistics': 'Statistics',
      'adherence_30d': 'Adherence (30d)',
      'overall_adherence': 'Overall Adherence',
      'missed_doses_30d': 'Missed Doses (30d)',
      'phase_progress': 'Phase Progress',
      'demo_notifications': 'Demo Notifications',
      'demo_notifications_subtitle':
          'Tap any button below to send a localized test notification to this device.',
      'send_notification': 'Send Notification',
      'demo_notification_sent': 'Notification sent',
      'daily_notification_reminder_title': 'Time to take your medication',
      'daily_notification_reminder_body':
          "Don't forget your TB treatment today. Staying consistent is key to recovery.",
      'missed_dose_alert_title': "You haven't taken your medication yet",
      'missed_dose_alert_body':
          "It's not too late. Taking your dose today helps keep your treatment on track.",
      'missed_dose_followup_title': "Did you miss yesterday's dose?",
      'missed_dose_followup_body':
          "Missing doses can affect your recovery. Try to stay consistent and take today's medication.",
      'please_log_in': 'Please log in',
      'log_symptoms': 'Log Symptoms',
      'select_symptoms': 'Select Symptoms',
      'severity': 'Severity',
      'notes_optional': 'Notes (Optional)',
      'add_notes': 'Add any additional notes...',
      'delete_entry': 'Delete Entry?',
      'delete_symptom_message':
          'Are you sure you want to delete this symptom log?',
      'symptom_log_deleted': 'Symptom log deleted',
      'symptom_log_saved': 'Symptom log saved',
      'error_saving_log': 'Error saving log',
      'error_deleting_log': 'Error deleting log',
      'user_not_logged_in': 'User not logged in',
      'entry': 'entry',
      'entries': 'entries',
      'no_entries_yet': 'No entries yet',
      'no_symptoms_logged_yet': 'No symptoms logged yet',
      'tap_add_to_record_symptoms':
          'Tap the add button to record how you are feeling today.',
      'symptoms_logged': 'symptoms logged',
      'mild': 'Mild',
      'moderate': 'Moderate',
      'severe': 'Severe',
      'nausea': 'Nausea',
      'cough': 'Cough',
      'vomiting': 'Vomiting',
      'fever': 'Fever',
      'fatigue': 'Fatigue',
      'chest_pain': 'Chest pain',
      'shortness_of_breath': 'Shortness of breath',
      'night_sweats': 'Night sweats',
      'exit_simple_mode': 'Exit Simple Mode',
      'simple_mode': 'Simple Mode',
      'patient_alerts': 'Patient Alerts',
      'no_alerts': 'No alerts',
      'all_patients_on_track': 'All patients are on track',
      'error': 'Error',
      'missed_doses_7d': 'Missed Doses - Last 7 Days',
      'need_immediate_attention': 'need immediate attention',
      'low_adherence': 'Low Adherence - Overall Treatment',
      'below_80_adherence': 'below 80% adherence',
      'add_patient': 'Add Patient',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'medication_name': 'Medication Name',
      'dosage': 'Dosage (e.g., 300 mg)',
      'frequency': 'Frequency (e.g., 1x/day)',
      'notes': 'Notes',
      'notes_optional_label': 'Notes (optional)',
      'eg_250mg': 'e.g., 250mg',
      'eg_twice_daily': 'e.g., Twice Daily',
      'generate_password': 'Generate 8-digit password',
      'phone_hint': '+1234567890',
      'confirm_logout': 'Confirm Logout',
      'practice_overview': 'Practice Overview',
      'total_patients': 'Total Patients',
      'low_adherence_count': 'Low Adherence',
      'call_patient': 'Call patient',
      'add_appointment': 'Add appointment',
      'title': 'Title',
      'date_time': 'Date & time',
      'appointments': 'Appointments',
      'upcoming_appointment': 'Upcoming Appointment',
      'add_appointment_to_phone_calendar_prompt':
          'Would you like to add this appointment to your phone calendar?',
      'appointment_not_added_to_calendar':
          'Appointment was not added to the calendar yet',
      'appointment_sent_to_calendar': 'Appointment sent to calendar',
      'failed_to_add_appointment': 'Failed to add appointment to calendar',
      'add_to_calendar': 'Add to Calendar',
      'appointment_available_singular': 'appointment available',
      'appointment_available_plural': 'appointments available',
      'no_appointments_scheduled': 'No appointments scheduled',
      'doctor_has_not_added_appointments':
          'Your doctor has not added any appointments yet.',
      'in_calendar': 'In calendar',
      'needs_add': 'Needs add',
      'yesterdays_medication': "Yesterday's Medication",
      'did_you_take_yesterday_medication':
          'Did you take your medication yesterday or did you miss it?',
      'taken': 'Taken',
      'missed': 'Missed',
      'todays_medication': "Today's Medication",
      'no_active_medications_scheduled_today':
          'No active medications scheduled today',
      'medication_scheduled_singular': 'medication scheduled',
      'medication_scheduled_plural': 'medications scheduled',
      'no_active_medications_for_today': 'No active medications for today.',
      'marked_as_taken_for_today': 'Marked as taken for today',
      'revert_choice': 'Revert Choice',
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'error_saving_dose_log': 'Error saving dose log',
      'error_reverting_choice': 'Error reverting choice',
      'error_updating_yesterday_log': 'Error updating yesterday log',
      'error_logging_out': 'Error logging out',
      'error_toggling_simple_mode': 'Error toggling simple mode',
      'track_weight': 'Track weight',
      'log_weight': 'Log Weight',
      'weight_value_kg': 'Weight (kg)',
      'recorded_on': 'Recorded on',
      'select_date': 'Select date',
      'save_weight': 'Save Weight',
      'enter_valid_weight': 'Enter a valid weight',
      'weight_saved': 'Weight saved',
      'weight_save_failed': 'Failed to save weight',
      'recent_weight_changes': 'Recent Weight Changes',
      'no_weight_logs': 'No weight entries yet',
      'no_change': 'No change',
    },
    'fr': {
      'settings': 'Paramètres',
      'language': 'Langue',
      'english': 'English',
      'french': 'Français',
      'arabic': 'العربية',
      'sign_out': 'Se déconnecter',
      'about': 'À propos',
      'tracking': 'Suivi',
      'treatment': 'Traitement',
      'symptoms': 'Symptôme',
      'insights': 'Aperçus',
      'profile': 'Profil',
      'simple_mode': 'Mode simple',
      'exit_simple_mode': 'Quitter le mode simple',
      'mark_taken': 'Marquer comme pris',
      'revert_choice': 'Annuler le choix',
      'current_streak': 'Série actuelle',
      'days': 'jours',
      'todays_medication': "Médicament d'aujourd'hui",
      'no_active_medications_scheduled_today':
          'Aucun médicament actif prévu aujourd’hui',
      'medication_scheduled_singular': 'Médicament programmé',
      'medication_scheduled_plural': 'Médicaments programmés',
      'no_active_medications_for_today':
          'Aucun médicament actif pour aujourd’hui.',
      'marked_as_taken_for_today': "Marqué comme pris aujourd'hui",
      'good_morning': 'Bonjour',
      'good_afternoon': 'Bon après-midi',
      'good_evening': 'Bonsoir',
      'error_saving_dose_log': "Erreur lors de l'enregistrement de la dose",
      'error_reverting_choice': "Erreur lors de l'annulation du choix",
      'demo_login': 'Connexion démo',
      'demo_doctor_login': 'Médecin démo',
      'demo_patient_1_login': 'Patient démo 1',
      'demo_patient_2_login': 'Patient démo 2',
      'sex_male': 'Homme',
      'sex_female': 'Femme',
      'statistics': 'Statistique',
      'goal': 'Objectif',
      'intensive_phase': 'Phase intensive',
      'continuation_phase': 'Phase de continuation',
      'weight': 'Poids',
      'treatment_start': 'Début du traitement',
      'treatment_overview': 'Aperçu du traitement',
      'current_phase': 'Phase actuelle',
      'day_in_treatment': 'Jour du traitement',
      'day': 'Jour',
      'days_left': 'Jours restants',
      'todays_dose': 'Dose du jour',
      'adherence_30d': 'Observance (30 jours)',
      'overall_adherence': 'Observance globale',
      'missed_doses_30d': 'Doses manquées (30 jours)',
      'phase_progress': 'Progression de phase',
      'demo_notifications': 'Notifications de démonstration',
      'demo_notifications_subtitle':
          'Appuyez sur un bouton ci-dessous pour envoyer une notification de test localisée sur cet appareil.',
      'send_notification': 'Envoyer la notification',
      'demo_notification_sent': 'Notification envoyée',
      'daily_notification_reminder_title': 'Il est temps de prendre votre traitement',
      'daily_notification_reminder_body':
          'N’oubliez pas votre traitement antituberculeux aujourd’hui. La régularité est essentielle pour guérir.',
      'missed_dose_alert_title': 'Vous n’avez pas encore pris votre traitement',
      'missed_dose_alert_body':
          'Il n’est pas trop tard. Prendre votre dose aujourd’hui aide à maintenir votre traitement efficace.',
      'missed_dose_followup_title': 'Avez-vous oublié votre dose d’hier ?',
      'missed_dose_followup_body':
          'L’oubli des doses peut affecter votre guérison. Essayez de rester régulier et prenez votre traitement aujourd’hui.',
      'erip_2_months': 'ERIP - 2 mois',
      'ri_4_months': 'RI - 4 mois',
      'appointments': 'Rendez-vous',
      'cancel': 'Annuler',
      'add': 'Ajouter',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'confirm': 'Confirmer',
      'exit_app': 'Quitter l’application ?',
      'exit_app_message': 'Voulez-vous vraiment quitter l’application ?',
      'exit': 'Quitter',
      'welcome': 'Bienvenue',
      'sign_in': 'Connectez-vous à votre compte',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'remember_me': 'Se souvenir de moi',
      'forgot_password': 'Mot de passe oubliée ?',
      'sign_in_button': 'Se connecter',
      'enter_email_required': 'Veuillez entrer votre e-mail',
      'enter_email_valid': 'Veuillez entrer une adresse e-mail valide',
      'enter_password_required': 'Veuillez entrer votre mot de passe',
      'password_min_6': 'Le mot de passe doit contenir au moins 6 caracteres',
      'dont_have_account': "Vous n'avez pas de compte ?",
      'sign_up': "S'inscrire",
      'logout_message': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'confirm_logout': 'Confirmer la déconnection',
      'track_weight': 'Suivre le poids',
      'log_weight': 'Enregistrer le poids',
      'weight_value_kg': 'Poids (kg)',
      'recorded_on': 'Enregistre le',
      'select_date': 'Choisir la date',
      'save_weight': 'Enregistrer le poids',
      'enter_valid_weight': 'Entrez un poids valide',
      'weight_saved': 'Poids enregistre',
      'weight_save_failed': "Echec de l'enregistrement du poids",
      'recent_weight_changes': 'Changements recents du poids',
      'no_weight_logs': 'Aucune entree de poids',
      'no_change': 'Aucun changement',
    },
    'ar': {
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      'sign_out': 'تسجيل الخروج',
      'account': 'الحساب',
      'about': 'حول',
      'help': 'المساعدة',
      'privacy': 'الخصوصية',
      'terms': 'الشروط',
      'dark_mode': 'الوضع الداكن',
      'notifications': 'الإشعارات',
      'app_name': 'Adhera',
      'welcome': 'مرحباً',
      'sign_in': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'remember_me': 'تذكرني',
      'forgot_password': 'نسيت كلمة المرور؟',
      'sign_in_button': 'تسجيل الدخول',
      'enter_email_required': 'يرجى إدخال البريد الإلكتروني',
      'enter_email_valid': 'يرجى إدخال بريد إلكتروني صحيح',
      'enter_password_required': 'يرجى إدخال كلمة المرور',
      'password_min_6': 'يرجى إدخال كلمة مرور تتكون من 6 أحرف على الأقل',
      'dont_have_account': 'ليس لديك حساب؟',
      'sign_up': 'تسجيل',
      'tracking': 'المتابعة',
      'add_dose': 'إضافة جرعة',
      'mark_taken': 'تم أخذ الجرعة',
      'medication': 'الدواء',
      'dose': 'الجرعة',
      'date': 'التاريخ',
      'time': 'الوقت',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'back': 'رجوع',
      'next': 'التالي',
      'previous': 'السابق',
      'confirm': 'تأكيد',
      'days': 'أيام',
      'kg_unit': 'كغم',
      'logout_message': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'successfully_signed_in': 'تم تسجيل الدخول بنجاح!',
      'incorrect_credentials':
          'البريد الإلكتروني أو كلمة المرور غير صحيح. حاول مرة أخرى.',
      'forgot_password_soon': 'سيتم إرسال تعليمات إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.',
      'demo_login': 'تسجيل الدخول تجريبي',
      'demo_doctor_login': 'طبيب تسجيل الدخول تجريبي',
      'demo_patient_1_login': 'مريض تسجيل الدخول تجريبي 1',
      'demo_patient_2_login': 'مريض تسجيل الدخول تجريبي 2',
      'sex_male': 'ذكر',
      'sex_female': 'أنثى',
      'exit_app': 'الخروج من التطبيق',
      'exit_app_message': 'هل أنت متأكد أنك تريد الخروج من التطبيق؟',
      'exit': 'خروج',
      'treatment': 'العلاج',
      'symptoms': 'الأعراض',
      'insights': 'الرؤى',
      'profile': 'الملف الشخصي',
      'patients': 'المصابين',
      'alerts': 'التنبيهات',
      'todays_dose': 'جرعة اليوم',
      'current_streak': 'السلسلة الحالية',
      'day': 'اليوم',
      'days_left': 'الأيام المتبقية',
      'patient_profile_not_found': 'لم يتم العثور على ملف المريض.',
      'unknown_patient': 'مريض غير معروف',
      'no_email': 'لا يوجد بريد إلكتروني',
      'age': 'العمر',
      'sex': 'الجنس',
      'not_set': 'غير محدد',
      'weight': 'الوزن',
      'treatment_start': 'بداية العلاج',
      'treatment_overview': 'نظرة عامة على العلاج',
      'current_phase': 'المرحله الحالية',
      'day_in_treatment': 'اليوم في العلاج',
      'of_180': ' من 180',
      'not_started': 'لم يبدأ',
      'treatment_calendar': 'تقويم العلاج',
      'calendar': 'التقويم',
      'protocol': 'البروتوكول',
      'track_treatment_journey':
          'تتبع كل يوم من رحلة العلاج ونشاطاتك.',
      'intensive_phase': 'المرحله المكثفة',
      'continuation_phase': 'مرحله الاستمرار',
      'phase_1_intensive': 'المرحله 1 - المكثفة (الأول شهرين)',
      'phase_2_continuation': 'المرحله 2 - الاستمرار (الشهور 3-6)',
      'erip_k4': 'ERIP-K4',
      'riniazide': 'RINIAZIDE',
      'erip_2_months': 'ERIP - 2 شهر',
      'ri_4_months': 'RI - 4 أشهر',
      'goal': 'الهدف',
      'remaining': 'المتبقي',
      'today': 'اليوم',
      'daily_timeline': 'الجدول اليومي',
      'your_treatment_timeline': 'الجدول العلاجي',
      'start_date': 'تاريخ البدء',
      'phase_2_begins': 'بداية المرحلة الثانية',
      'expected_end': 'النهاية المتوقعة',
      'important': 'مهم',
      'what_this_means_for_you': 'ما يعنيه هذا بالنسبة لك',
      'what_you_may_notice': 'ما قد تلاحظه',
      'why_multiple_medications': 'لماذا أدوية متعددة',
      'why_continue_treatment': 'لماذا الاستمرار في العلاج',
      'please_sign_in': 'يرجى تسجيل الدخول لتسجيل التقدم في العلاج.',
      'statistics': 'الإحصائيات',
      'adherence_30d': 'الالتزام (30 يوم)',
      'overall_adherence': 'الالتزام العام',
      'missed_doses_30d': 'الجرعات المفقودة (30 يوم)',
      'phase_progress': 'تقدم المرحلة',
      'please_log_in': 'يرجى تسجيل الدخول',
      'log_symptoms': 'تسجيل الأعراض',
      'select_symptoms': 'اختيار الأعراض',
      'severity': 'الشدة',
      'notes_optional': 'ملاحظات (اختياري)',
      'add_notes': 'إضافة ملاحظات...',
      'delete_entry': 'حذف الإدخال',
      'delete_symptom_message': 'هل أنت متأكد من حذف سجل الأعراض هذا؟',
      'symptom_log_deleted': 'تم حذف سجل الأعراض',
      'symptom_log_saved': 'تم حفظ سجل الأعراض',
      'error_saving_log': 'حدث خطأ أثناء حفظ السجل',
      'error_deleting_log': 'حدث خطأ أثناء حذف السجل',
      'user_not_logged_in': 'المستخدم غير مسجل الدخول',
      'entry': 'سجل',
      'entries': 'سجلات',
      'no_entries_yet': 'لا توجد سجلات بعد',
      'no_symptoms_logged_yet': 'لا توجد أعراض مسجلة بعد',
      'tap_add_to_record_symptoms': 'اضغط لإضافة الأعراض للتسجيل',
      'symptoms_logged': 'الأعراض المسجلة',
      'mild': 'خفيف',
      'moderate': 'متوسط',
      'severe': 'شديد',
      'nausea': 'غثيان',
      'cough': 'سعال',
      'vomiting': 'قيء',
      'fever': 'حمى',
      'fatigue': 'تعب',
      'chest_pain': 'ألم الصدر',
      'shortness_of_breath': 'ضيق التنفس',
      'night_sweats': 'العرق الليلي',
      'exit_simple_mode': 'الخروج من الوضع البسيط',
      'simple_mode': 'الوضع البسيط',
      'patient_alerts': 'تنبيهات المريض',
      'no_alerts': 'لا توجد تنبيهات',
      'all_patients_on_track': 'جميع المرضى على المسار',
      'error': 'خطأ',
      'missed_doses_7d': 'الجرعات المفقودة - آخر 7 أيام',
      'need_immediate_attention': 'يتطلب اهتماماً فورياً',
      'low_adherence': 'الالتزام المنخفض - الوضع الكلي',
      'below_80_adherence': 'أقل من 80% الالتزام',
      'add_patient': 'إضافة مريض',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'medication_name': 'اسم الدواء',
      'dosage': 'الجرعة (مثال: 300 ملغ)',
      'frequency': 'التكرار (مثال: صباحاً/الجمعة)',
      'notes': 'ملاحظات',
      'notes_optional_label': 'ملاحظات (اختياري)',
      'eg_250mg': 'مثال: 250mg',
      'eg_twice_daily': 'مثال: مرتين يومياً',
      'generate_password': 'إنشاء كلمة مرور من 8 أحرف',
      'phone_hint': '+1234567890',
      'confirm_logout': 'تأكيد تسجيل الخروج',
      'track_weight': 'تتبع الوزن',
      'log_weight': 'تسجيل الوزن',
      'weight_value_kg': 'الوزن (كغ)',
      'recorded_on': 'مسجل في',
      'select_date': '\u0627\u062E\u062A\u064A\u0627\u0631 \u062A\u0627\u0631\u064A\u062E',
      'save_weight': '\u062D\u0641\u0638 \u0627\u0644\u0648\u0632\u0646',
      'enter_valid_weight': '\u0623\u062F\u062E\u0644 \u0648\u0632\u0646\u0627 \u0635\u062D\u064A\u062D\u0627',
      'weight_saved': '\u062A\u0645 \u062D\u0641\u0638 \u0627\u0644\u0648\u0632\u0646',
      'weight_save_failed': '\u0641\u0634\u0644 \u062D\u0641\u0638 \u0627\u0644\u0648\u0632\u0646',
      'recent_weight_changes': '\u0627\u0644\u062A\u063A\u064A\u0631\u0627\u062A \u0627\u0644\u0623\u062E\u064A\u0631\u0629 \u0641\u064A \u0627\u0644\u0648\u0632\u0646',
      'no_weight_logs': '\u0644\u0627 \u062A\u0648\u062C\u062F \u062A\u0633\u062C\u064A\u0644\u0627\u062A \u0648\u0632\u0646',
      'no_change': '\u0644\u0627 \u062A\u063A\u064A\u064A\u0631',
      'practice_overview': 'نظرة عامة على الممارسة',
      'total_patients': 'إجمالي المرضى',
      'low_adherence_count': 'الالتزام المنخفض',
      'call_patient': 'اتصال بالمرضى',
      'add_appointment': 'إضافة موعد',
      'title': 'العنوان',
      'date_time': 'التاريخ والوقت',
      'appointments': 'المواعيد',
      'upcoming_appointment': 'الموعد القادم',
      'add_appointment_to_phone_calendar_prompt':
          'هل ترغب في إضافة هذا الموعد إلى تقويم هاتفك؟',
      'appointment_not_added_to_calendar':
          'لم تتم إضافة الموعد إلى تقويم هاتفك',
      'appointment_sent_to_calendar': 'تم إرسال الموعد إلى تقويم هاتفك',
      'failed_to_add_appointment': 'فشل في إضافة الموعد إلى تقويم هاتفك',
      'add_to_calendar': 'إضافة إلى التقويم',
      'appointment_available_singular': 'موعد متاح',
      'appointment_available_plural': 'مواعيد متاحة',
      'no_appointments_scheduled': 'لا توجد مواعيد مجدولة',
      'doctor_has_not_added_appointments': 'الدكتور لم يضيف أي مواعيد.',
      'in_calendar': 'في التقويم',
      'needs_add': ' حاجة لإضافة',
      'yesterdays_medication': 'دواء الأمس',
      'did_you_take_yesterday_medication':
          'هل أخذت دوائك بالأمس؟',
      'taken': 'تم أخذها',
      'missed': 'فوت',
      'todays_medication': 'دواء اليوم',
      'no_active_medications_scheduled_today':
          'لا توجد أدوية نشطة مجدولة لليوم',
      'medication_scheduled_singular': 'دواء مجدول',
      'medication_scheduled_plural': 'أدوية مجدولة',
      'no_active_medications_for_today': 'لا توجد أدوية نشطة لليوم.',
      'marked_as_taken_for_today': 'تم وضع علامة كمأخوذ لليوم',
      'revert_choice': 'ترجيع الاختيار',
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',
      'error_saving_dose_log': 'خطأ في حفظ سجل الجرعة',
      'error_reverting_choice': 'خطأ في ترجيع الاختيار',
      'error_updating_yesterday_log': 'خطأ في تحديث سجل الأمس',
      'error_logging_out': 'خطأ في تسجيل الخروج',
      'error_toggling_simple_mode': 'خطأ في تبديل الوضع البسيط',
    },
  };

  static String translate(String key, {String locale = 'en'}) {
    return translations[locale]?[key] ?? translations['en']?[key] ?? key;
  }

  String t(String key) {
    return translate(key, locale: _locale.languageCode);
  }
}

extension TranslationExtension on BuildContext {
  String t(String key) {
    return LocalizationService().t(key);
  }
}

