// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVIeeepK86kE5I4EsmbJKvGJ-UNb7-M9c',
    appId: '1:61562203916:web:54586396258ff994c2a329',
    messagingSenderId: '61562203916',
    projectId: 'tb-pneumo',
    authDomain: 'tb-pneumo.firebaseapp.com',
    storageBucket: 'tb-pneumo.firebasestorage.app',
    measurementId: 'G-8X62YYMNN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkDRWUn2RbECN2hG8cE0fXx418rx4EiTk',
    appId: '1:61562203916:android:965ad7a7224f56e9c2a329',
    messagingSenderId: '61562203916',
    projectId: 'tb-pneumo',
    storageBucket: 'tb-pneumo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1eymJ-j6Jll_uMyiT7hKMvwKmtJMK4BQ',
    appId: '1:61562203916:ios:8e812c4cb860727ec2a329',
    messagingSenderId: '61562203916',
    projectId: 'tb-pneumo',
    storageBucket: 'tb-pneumo.firebasestorage.app',
    iosBundleId: 'com.highui.adhera',
  );

}